name: wiires_tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install
      run: python -m pip install "git+https://github.com/dpinney/wiires"
    - name: DEBUG
      run: python -c 'import windpowerlib; print(dir(windpowerlib)); print(windpowerlib.__version__)'
    - name: Test
      run: python -c 'import wiires'
